CREATE TABLE banners (
	id BIGSERIAL PRIMARY KEY,
	title TEXT NOT NULL,
	content TEXT NOT NULL,
	button TEXT NOT NULL,
	link TEXT NOT NULL,
	image TEXT NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE banners (
	id BIGSERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	price INTEGER NOT NULL CHECK (price > 0),
	qty INTEGER NOT NULL DEFAULT 0 CHECK (qty >= 0),
	active BOOLEAN NOT NULL DEFAULT TRUE,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customers (
	id BIGSERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	phone TEXT NOT NULL UNIQUE,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);