CREATE TABLE banners (
	id BIGSERIAL PRIMARY KEY,
	title TEXT NOT NULL,
	content TEXT NOT NULL,
	button TEXT NOT NULL,
	link TEXT NOT NULL,
	image TEXT NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
	id BIGSERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	price INTEGER NOT NULL CHECK (price > 0),
	qty INTEGER NOT NULL DEFAULT 0 CHECK (qty >= 0),
	active BOOLEAN NOT NULL DEFAULT TRUE,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customers (
	id BIGSERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	phone TEXT NOT NULL UNIQUE,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE managers (
	id BIGSERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	salary INTEGER NOT NULL CHECK (salary > 0),
	plan INTEGER NOT NULL CHECK (plan > 0),
	boss_id BIGINT REFERENCES managers,
	department TEXT,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sales (
	id BIGSERIAL PRIMARY KEY,
	manager_id BIGINT NOT NULL REFERENCES managers,
	customer_id BIGINT REFERENCES customers,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sale_positions (
	id BIGSERIAL PRIMARY KEY,
	sale_id BIGINT NOT NULL REFERENCES sales,
	product_id BIGINT NOT NULL REFERENCES products,
	name TEXT NOT NULL,
	price INTEGER NOT NULL CHECK (price > 0),
	qty INTEGER NOT NULL DEFAULT 0 CHECK (qty >= 0),
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


